version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5000:5000
  backend:
    container_name: backend
    build: ./backend
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379