version: '3.8'

services:
  express_app:
    image: e1900311/express:latest
    container_name: express_app
    restart: always
    ports:
      - '8080:8080'

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 express_app