version: '3.8'

# removed the exposed ports from the backend and frontend containers
services:
  frontend:
    container_name: frontend
    build: ./frontend
  backend:
    container_name: backend
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf